---
title: "Health and Economic damage of weather events between 1950-2011"
author: "Victor Bucha"
date: "23 September 2015"
output: html_document
keep_md: true
---
#Synopsis
In this report we studied health and economic damages of weather events between 1950-2011 in US. We found that Tornado event made the most damge to the population health (injuries and fatalities).Floods and hurricanes made the most damge in economic domain (property and crop). 

#Data Processing 
##Reading the data
Let us load needed packages. Data.table package is used for fast .csv file loading.
``` {R load packages}
library(data.table)
library(dplyr,warn.conflicts=FALSE)
library(ggplot2)
library(tidyr)
library(R.utils)
```

At first, let us check raw data file in a working directory. If it does not exsist download and unpack it.
``` {R check raw data file}
URLdata="https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
rawfilenamebz2="repdata-data-StormData.csv.bz2"
rawfilename="repdata-data-StormData.csv"

# if raw data is not present in working folder, download and unpack it
if (!file.exists(rawfilename)){
        if (!file.exists(rawfilenamebz2))
                download.file(URLdata,rawfilenamebz2)
        else
                bunzip2(rawfilenamebz2, destname = rawfilename, remove = FALSE)
}
```

``` {R loadingdata,cache=TRUE}        
# read csv from connection
df.raw<-fread("repdata-data-StormData.csv",
        sep=",",header=TRUE,verbose = FALSE,na.strings ="",stringsAsFactors=TRUE)
```
### Select relevant columns
Data relevant to the assignment is stored in a few columns:  
- EVTYPE  
- FATALITIES  
- INJURIES  
- PROPDMG  
- PROPDMGEXP  
- CROPDMG  
- CROPDMGEXP   
In addition, we have interest in values greather than 0. Let us select only needed colunms and filter out non-zero values in order to save system resources for further processing.
``` {R basic cleaning}
relevant.columns<-df.raw %>% select(EVTYPE,FATALITIES:CROPDMGEXP) %>% 
        filter(FATALITIES>0|INJURIES>0|PROPDMG>0|CROPDMG>0)

```

### Combine duplicated events
The event type is stored in EVTYPES column. There are many duplicated types of events. Let us combine duplicated types together and store result in a new column BTYPE.
``` {R merge duplicated EVTYPES}
f<-(relevant.columns$EVTYPE)
f[grepl("wind",f,ignore.case = TRUE)]="WIND"
f[grepl("rain",f,ignore.case = TRUE)]="RAIN"
f[grepl("flood",f,ignore.case = TRUE)]="FLOOD"
f[grepl("heat",f,ignore.case = TRUE)]="HEAT"
f[grepl("cold",f,ignore.case = TRUE)]="COLD"
f[grepl("lightning",f,ignore.case = TRUE)]="LIGHTNING"
f[grepl("tornado",f,ignore.case = TRUE)]="TORNADO"
f[grepl("snow|blizzard",f,ignore.case = TRUE)]="SNOW"
f[grepl("hurricane|tropical",f,ignore.case = TRUE)]="HURRICANE"
f[grepl("hail",f,ignore.case = TRUE)]="HAIL"
#create new column BTYPE that has wider categories without duplication
relevant.columns$BTYPE<-f
```

### Convert damage to floating point estimate
Economical damage includes property and crop damages. We will estimate total economic damage as a sum of property and crop damage. The damage value is represented in two parts - mantissa and exponenta. Mantissa is stored in PROPDMG and CROPDMG fields. Exponenta is stored in PROPDMGEXP and CROPDMGEXP. Exponenta is coded with character "K"=1e3,"M"=1e6,"B"=1e9. Other codes of exponent were not defined in a reference document clearly, so we ignore that records. Let us convert damage to proper numeric value and store it in PROPERTY.DMG and CROP.DMG columns.

``` {R convert damage to numeric}
#define lookup table for exponent
lookup<-c(K=1000,M=1e6,B=1e9)
#define function to handle NA values
convert_NA<-function (col) {c<-as.character(col);c[is.na(c)]="NA";c}
#convert NA values to character "NA" in order to speed-up further mutate execution
relevant.columns$PROPDMGEXP<-convert_NA(relevant.columns$PROPDMGEXP)
relevant.columns$CROPDMGEXP<-convert_NA(relevant.columns$CROPDMGEXP)

damage_converted<-relevant.columns %>% 
        mutate(PROPERTY.DMG=ifelse(toupper(PROPDMGEXP) %in% names(lookup),
                                       lookup[toupper(PROPDMGEXP)]*PROPDMG,0),
               CROP.DMG=ifelse(toupper(CROPDMGEXP) %in% names(lookup),
                               lookup[toupper(CROPDMGEXP)]*CROPDMG,0)) %>%
        select (-c(PROPDMGEXP,PROPDMG,CROPDMGEXP,CROPDMG))
```
### Estimate health and economic damages for each event type
``` {R Summarization of health and economic damages}
damage<-damage_converted %>% group_by(BTYPE) %>% 
        summarise(INJURIES=sum(INJURIES),FATALITIES=sum(FATALITIES),
                  PROPERTY=sum(PROPERTY.DMG)/10e6,CROP=sum(CROP.DMG)/10e6) %>%
        mutate(TOTAL_HEALTH=INJURIES+FATALITIES,
               TOTAL_ECONOMIC=(PROPERTY+CROP))

```

#Results
##Question 1. Most harmful event type with respect to population health
``` {R answer Q1 question}
damage<-damage %>% arrange(-TOTAL_HEALTH)
top10.harm_health<-damage[1:10] %>%
        select(BTYPE,INJURIES,FATALITIES,TOTAL_HEALTH) %>%
        gather(DAMAGE.TYPE,COUNT,-c(BTYPE,TOTAL_HEALTH))

#sort factor in descending order ot total health damage
top10.harm_health$BTYPE<-with (top10.harm_health,reorder(BTYPE,-TOTAL_HEALTH))

#draw plot
ggplot(top10.harm_health,aes(x=BTYPE,y=COUNT,fill=DAMAGE.TYPE))+
        geom_bar(stat = "identity")+
        theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+
        labs(title="Total population health damage in US. 1950-2011 ",x="Event",y="Count")
```

##Question 1. Most harmful event type with respect to economic consequences
``` {R answer Q2 question}
damage<-damage %>% arrange(-TOTAL_ECONOMIC)

top10.harm_econ<-damage[1:10] %>%
        select(BTYPE,PROPERTY,CROP,TOTAL_ECONOMIC) %>%
        gather(DAMAGE.TYPE,COUNT,-c(BTYPE,TOTAL_ECONOMIC))

#sort factor in descending order ot total health damage
top10.harm_econ$BTYPE<-with (top10.harm_econ,reorder(BTYPE,-TOTAL_ECONOMIC))

#draw plot
ggplot(top10.harm_econ,aes(x=BTYPE,y=COUNT,fill=DAMAGE.TYPE))+
        geom_bar(stat = "identity")+
        theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))+
        labs(title="Total economic damage in US. 1950-2011",x="Event",y="US Dollars (in millions)")
```
